use crate::util::{ProjectScope, is_installed};
use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Copy)]
pub enum PythonPm {
    Pip,
    Uv,
    None,
}

#[derive(Deserialize, Debug)]
pub(crate) struct PyProject {
    project: Option<ProjectTable>,
    // The new standard (PEP 735)
    #[serde(rename = "dependency-groups")]
    dependency_groups: Option<HashMap<String, Vec<String>>>,
    // The specific tool tables
    tool: Option<ToolTable>,
}

#[derive(Deserialize, Debug)]
struct ProjectTable {
    dependencies: Option<Vec<String>>,
}

#[derive(Deserialize, Debug)]
struct ToolTable {
    // Handling the legacy uv fields
    uv: Option<UvTable>,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "kebab-case")]
struct UvTable {
    dev_dependencies: Option<Vec<String>>,
}

pub(crate) fn get_python_project_scope(target: &Path, project_name: &str) -> ProjectScope {
    if target.join("pyproject.toml").exists()
        && target
            .join(format!("src/{project_name}/__init__.py"))
            .exists()
    {
        ProjectScope::Install
    } else if target.join("pyproject.toml").exists() || target.join("requirements.txt").exists() {
        ProjectScope::Requirements
    } else {
        ProjectScope::Base
    }
}

pub(crate) fn get_python_manager(version: &str) -> PythonPm {
    if is_installed("uv") {
        return PythonPm::Uv;
    }
    if is_installed(&format!("python{version}").to_string()) {
        return PythonPm::Pip;
    }
    PythonPm::None
}

pub(crate) fn parse_pyproject(pyproject_path: &Path) -> Result<PyProject> {
    if !pyproject_path.exists() {
        bail!("This shoud not have happened, how did we get here?!")
    }
    let content = fs::read_to_string(pyproject_path).context(format!(
        "Could not pyproject toml at {}",
        pyproject_path.display()
    ))?;
    let pyrproject: PyProject = toml::from_str(&content)?;
    Ok(pyrproject)
}

pub(crate) fn requirements_from_pyproject(target: &Path) -> Result<Vec<String>> {
    let pyproject_path = target.join("pyproject.toml");
    let pyproject = parse_pyproject(&pyproject_path)?;
    let mut requirements: Vec<String> = Vec::new();
    if let Some(project_deps) = pyproject.project.and_then(|x| x.dependencies) {
        requirements.extend(project_deps);
    }
    if let Some(group_deps) = pyproject.dependency_groups {
        for (_, dep_list) in group_deps {
            requirements.extend(dep_list);
        }
    }
    if let Some(uv_deps) = pyproject
        .tool
        .and_then(|t| t.uv)
        .and_then(|uv| uv.dev_dependencies)
    {
        requirements.extend(uv_deps);
    }
    Ok(requirements)
}

pub(crate) fn dev_groups_from_pyproject(target: &Path) -> Result<Vec<String>> {
    let pyproject_path = target.join("pyproject.toml");
    let pyproject = parse_pyproject(&pyproject_path)?;
    let mut dev_groups: Vec<String> = Vec::new();
    if let Some(group_deps) = pyproject.dependency_groups {
        for (group, _) in group_deps {
            dev_groups.push(group);
        }
    }
    Ok(dev_groups)
}

pub(crate) fn ensure_requirements(target: &Path) -> Result<bool> {
    let req_file = target.join("requirements.txt");
    if !req_file.exists() {
        let plato_hidden_path = target.join(".plato/");
        let plato_req_file = target.join(".plato/requirements.txt");
        let requirements = requirements_from_pyproject(target)?;
        let file_content = requirements.join("\n");
        let _ = fs::create_dir_all(plato_hidden_path);
        let _ = fs::write(&plato_req_file, file_content);

        println!(
            "Generating requirements.txt at {} to satisfy pip",
            &plato_req_file.display()
        );
        return Ok(true);
    }
    Ok(false)
}

pub(crate) fn ensure_readme(target: &Path) -> Result<()> {
    let readme = target.join("README.md");
    if !readme.exists() {
        println!(
            "Generating basic readme at {} to satisfy pip",
            &readme.display()
        );
        fs::write(readme, "# Basic readme generated by Plato")?;
    }
    Ok(())
}
